import pandas as pd

configfile: "../config/config.yaml"

samples = pd.read_csv(config["samples_tsv"], sep="\t")
sample_names = samples["sample"].tolist()

include: "rules/download.smk"
include: "rules/fastq_gunzip.smk"
include: "rules/trim.smk"
include: "rules/spades.smk"

include: "rules/fasta_to_db.smk"
include: "rules/mmseqs2_taxonomy.smk"
include: "rules/to_tsv.smk"
include: "rules/filter.smk"

#clustering
include: "rules/clustering/filter_fasta.smk"
include: "rules/clustering/make_blast_db.smk"
include: "rules/clustering/blastn.smk"
include: "rules/clustering/process_blast.smk"
include: "rules/clustering/sort_blast.smk"
include: "rules/clustering/anicalc.smk"
include: "rules/clustering/aniclust.smk"
include: "rules/clustering/reps.smk"

#mapping
include: "rules/mapping/bwa.smk"
include: "rules/mapping/coverm.smk"


rule all:
    input:
        expand("../results/{sample}/{sample}_coverm.tsv", sample=sample_names),


   

  